sudo: required
service:
  - docker
before_install:
  - docker build -t vvineethmenon/travis_test:v1.0 .
script:
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker images #to_verify
  - docker push vvineethmenon/travis_test:v1.0 
notification:
 email:
    recipients:
      - vineethmenon287@gmail.com
   on_success: always
   on_failure: always
